### ISSUE TITLE
Issue with featured images in latest news area

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/llorix-one-lite#104] opened 2016-10-06 04:06 UTC
@rodica-andronache image doesn't fit in circle in latest update: http://prnt.sc/cqe0b2

**Comment by rodica-andronache** [comment] 2016-10-06 14:45
@UVLabs did you test this or it was just reported by the user?

**Comment by UVLabs** [comment] 2016-10-06 20:25
Reported and I tested myself @rodica-andronache

**Comment by claudiuvertistudio** [comment] 2016-10-20 12:16
I have tested and seems to work well

**Comment by UVLabs** [comment] 2016-10-26 02:21
@HardeepAsrani @Basilakis could you guys check?

**Comment by HardeepAsrani** [comment] 2016-10-28 19:07
Can't reproduce.

**Comment by rodica-andronache** [comment] 2016-11-08 12:22
@UVLabs I'll close this as we can't replicate. if you find out more details let me know

**Closed by rodica-andronache** 2016-11-08 12:22 UTC
Labels: bug, investigation
